import cv2
from Code import PATHS
from keras.layers import GlobalAveragePooling2D
from keras.utils import load_img
from tensorflow.keras.models import Sequential, load_model, Model, clone_model
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
from keras.applications.resnet import ResNet50
from sys import platform
import pickle
import datetime
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import *
tf.random.set_seed(1)   # For reproducibility
np.random.seed(1)

def get_resize_layer(target_shape):
    layer = Lambda(lambda x: tf.image.resize(x, (target_shape[0], target_shape[1])))
    layer._name = 'up-sample_layer'
    return layer

def join_models(obfuscation_model, inference_model):
    """
    Join an obfuscation model and an inference model into a combined model.

    Parameters:
    - obfuscation_model (Sequential): The obfuscation model.
    - inference_model (Sequential): The inference model.

    Returns:
    Sequential: The combined model.

    Raises:
    Exception: If the input and output shapes of the obfuscation model are not equal to the input shape of the inference model.
    """
    # Make sure that the input of the obfuscation model is equal to the output of the inference model
    if obfuscation_model.input_shape != inference_model.input_shape or obfuscation_model.output_shape != inference_model.input_shape:
        raise Exception('The input and output shapes of the obfuscation model are not equal to the input shape of the inference model')

    obfnet_name = obfuscation_model.name
    combined_model = Sequential(name=obfnet_name)
    combined_model.add(obfuscation_model)
    combined_model.add(inference_model)
    combined_model.layers[0]._name = 'ObfModel'
    combined_model.layers[1]._name = 'InfModel'
    return combined_model

def split_models(combined_model):
    """
    Split a combined model into its obfuscation model and inference model components.

    Parameters:
    - combined_model (Sequential): The combined model containing both obfuscation and inference models.

    Returns:
    tuple: A tuple containing the obfuscation model and the inference model.

    Raises:
    Exception: If the number of layers in the combined model is not 2.
    Exception: If 'ObfModel' is not found as the first layer in the combined model.
    Exception: If 'InfModel' is not found as the second layer in the combined model.

    Note:
    This function only works with combined models generated by join_models() function
    """
    if len(combined_model.layers) != 2:
        raise Exception('Wrong layer size, must be 2')
    if combined_model.layers[0].name != 'ObfModel':
        raise Exception('ObfModel was not found in the combined model')
    if combined_model.layers[1].name != 'InfModel':
        raise Exception('InfModel was not found in the combined model')
    return combined_model.layers[0], combined_model.layers[1]

def freeze_inf_model(combined_model):
    """
    Freeze the inference model within a combined model by setting its layers as non-trainable.

    Parameters:
    - combined_model (Sequential): The combined model containing both obfuscation and inference models.

    Returns:
    None

    Raises:
    Exception: If the number of layers in the combined model is not 2.
    Exception: If 'ObfModel' is not found as the first layer in the combined model.
    Exception: If 'InfModel' is not found as the second layer in the combined model.

    Note:
    This function only works with combined models generated by join_models() function
    """
    if len(combined_model.layers) != 2:
        raise Exception('Wrong layer size, must be 2')
    if combined_model.layers[0].name != 'ObfModel':
        raise Exception('ObfModel was not found in the combined model')
    if combined_model.layers[1].name != 'InfModel':
        raise Exception('InfModel was not found in the combined model')

    # Freeze the last layer of the inference model
    combined_model.layers[1].trainable = False


def get_pretrained_ResNet50(weights_dir):
    """
    Load a pre-trained ResNet50 model with weights trained on ImageNet.
    This version of ResNet50 was retrained to work with only 10 classes

    Parameters:
    - weights_dir (String): The path to the .h5 weights file

    Returns:
    Model: A pre-trained ResNet50 model.
    """
    # Load the ResNet50 model with pre-trained weights
    base_model = ResNet50(weights=None, include_top=False, input_shape=(224, 224, 3))

    # Add custom classification layers
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(1024, activation='relu')(x)
    x = Dense(512, activation='relu')(x)
    predictions = Dense(10, activation='softmax')(x)

    # Create the final model
    model = Model(inputs=base_model.input, outputs=predictions)
    model.load_weights(weights_dir)
    return model

if __name__ == "__main__":
    model = get_pretrained_ResNet50(PATHS.RESNET_WEIGHTS)
    model.summary()
